### ISSUE TITLE
Supervisor fails when it shouldn't

### ISSUE THREAD

**Issue by chshersh** [roman/Haskell-capataz#26]
Consider the following code that uses the `capataz` library:

* https://gist.github.com/ChShersh/7ce645338c961869757262652b39492d

This code creates supervisor and two threads:

* Thread 1: does nothing, waits infinitely
* Thread 2: waits random time from 1 to 3 seconds and throws an exception

### Observed behaviour

Main thread exits

### Expected behaviour

Supervisor tries to restart failing worker infinitely.

Here are the logs:

* https://lpaste.net/8240404574289002496

**Comment by chshersh** [comment]
Okay, I've figured out the fix by myself. The trick is to add something like this to `forkCapataz`:

```haskell
             . set supervisorIntensityL maxBound
             . set supervisorPeriodSecondsL 1
```

Basically this will tell that supervisor won't die unless it receives more than infinity (well, almost) exceptions for single second.

**Comment by roman** [comment]
@ChShersh Yes, the [default supervisor strategy](https://github.com/roman/Haskell-capataz/blob/master/src/Control/Concurrent/Capataz/Internal/Types.hs#L905) is prone to raise (2 errors every 5 seconds). I would not set the intensity so high unless you are expecting your supervised threads to fail all the time, a red flag IMO

**Comment by roman** [comment]
Also, any feedback in UX of the API is very welcome
