### ISSUE TITLE
Support GHC-8.6.3

### ISSUE THREAD

**Issue by vrom911** [roman/Haskell-capataz#27]
I tried to make it myself but some decisions should be made in here.

The thing is that the latest version of `stm` –– [`stm-2.5.0.0`](http://hackage.haskell.org/package/stm-2.5.0.0) has some breaking change in it, so the interface of the `capataz` library is conflicting with it. The Changelog for 2.5.0.0 says

> Switched newTBQueue and newTBQueueIO to accept Natural as size (gh-17)

And here is the error for `capataz`:

```haskell
Haskell-capataz/src/Control/Concurrent/Capataz/Util.hs:75:30: error:
        • Couldn't match expected type ‘Natural’ with actual type ‘Int’
        • In the first argument of ‘newTBQueueIO’, namely ‘bufferSize’
          In a stmt of a 'do' block: inputQueue <- newTBQueueIO bufferSize
          In the expression:
            do inputQueue <- newTBQueueIO bufferSize
               let myLogFunc = mkLogFunc $ ...
                   loggerSpec
                     = workerSpec
                         procName
                         (runLoggerThread logOptions inputQueue)
                         (modOptions . set workerRestartStrategyL Permanent)
               return (loggerSpec, myLogFunc)
       |
    75 |   inputQueue <- newTBQueueIO bufferSize
       |                              ^^^^^^^^^^
```

The old version of `stm` -- 2.4.5.1 is not compatible with GHC-8.6.3.
So I'm not sure how you'd like this to be solved but either way, this is going to be breaking for `capataz`, so the new release should be made in order to support building with GHC-8.6.3.

If you'd like I can continue working on this if we agree on the strategy. The question is: is it better to change the type of the `buildLogWorkerSpec` to receive `Natural` or only change the internal of the function?  Or probably you have some better ways to solve this?

**Comment by roman** [comment]
Hey @vrom911,

Thank you for looking at this 🙇‍♂️

> The question is: is it better to change the type of the buildLogWorkerSpec to receive Natural or only change the internal of the function? Or probably you have some better ways to solve this?

What do you think about:

* Add a new function called `buildLogWorkerSpec1` (or another name that you see makes more sense) that receives the `Natural` parameter, no need to change the code.

* Modify `buildLogWorkerSpec` to do a transformation from `Int` to `Natural` internally (if it is possible) inside the function. At the same time, add a deprecation pragma to this function and add to its documentation that we have deprecated this function in favor of `buildLogWorkerSpec1` and that it will throw a runtime error if the given `Int` is _not_ a `Natural`.

Let me know your thoughts.

**Comment by vrom911** [comment]
Sounds good! I will use this approach in the following PR.

**Comment by roman** [comment]
Hey  @vrom911 apologies for letting this drag, I've been changing jobs in the past week and it has been a bit crazy, I'll try to address this in the next couple of days, thank you for bearing with me

**Comment by vrom911** [comment]
I see, no rush in here, @roman! Take your time 🙂
